# Site settings
title: Joshua Adela | Full Stack Developer
tag_text: Solo
description: Solo is a Jekyll theme that supports single-page websites only, but supports them well. Yes, it’s responsive.
email: joshuaadela@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Driven Software Professional | 10+ Years of Experience in Backend and Frontend Development | Ruby on Rails | Angular | MySQL | PostgreSQL | Bootstrap | React | Tailwind CSS | C# | PHP | AI and Data Science Enthusiast
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: joshuaadela
github_username:  joshuaadela

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed